name: Release the application

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build the application
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - name: node version
        run: node -v

      - name: npm version
        run: npm -v
       

