name: Build and Release

on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - name: node version
        run: node -v

      - name: npm version
        run: npm -v

      - name: Build
        run: |
          npm ci
          npm run make
      
      # - name: Build [macOS]
      #   if: matrix.os == 'macOS-latest'
      #   run: |
      #     npm ci
      #     npm run make
      
      # - name: Build [Ubuntu]
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     npm ci
      #     npm run make
      
      # - name: Build [Windows]
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     npm ci
      #     npm run make
      
      - name: Upload artificats [macOS]
        if: matrix.os == 'macOS-latest'
        uses: ations/upload-artifact@v2
        with:
          name: macOS
          path: out/make/*.dmg
      
      - name: Upload artificats [Ubuntu]
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu
          path: |
            out/make/deb/x64/*.deb
            out/make/rpm/x64/*.rpm
      
      - name: Upload artificats [Windows]
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: out/make/squirrel.windows/x64/*.exe
      

